'''
the following is a password generator function.
User defines how many characters the pasword should contain, with a hard minimum of 12.
Password contains a random assortment of at least one of each: special characters, numbers, lowercase and uppercase letters.
'''
import random
from random import shuffle

def generatePassword(length):
  #turns each string into a list
  Special=list('~!@#$%^&*()_+')
  Number = list('1234567890')
  Lowercase = list('abcdefghijklmnopqrstuvwxyz')
  Uppercase = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
  #randomize order of lists of characters.
  characterTypes = random.sample([Special, Number, Lowercase, Uppercase],4)
  #empty list where keys are stored
  Keys=[]
  #set minimum password length to 12
  if length < 12:
    length = 12
  #count down number of keys that need to be generated. Determined by length argument.
  toGenerate = length
  #while loop refers to the number of keys to be generated
  while toGenerate > 0:
    #itrate through the list of lists of character types.
    for types in characterTypes:
      #randomize which charcter is picked
      index=random.randint(0,(len(types)-1))
      #add character to key list
      Keys.append(types[index])
      #subtracts number of keys to be generated by 1
      toGenerate -=1
  
  #randomize order of keys
  Keys=random.sample(Keys,length)
  #turn list of keys into a string
  Keys=''.join(Keys)
  return(Keys)

print(generatePassword(9))


'''
tests
'''
pw = generatePassword(14)

assert len(pw) == 14

hasLowercase = False

hasUppercase = False

hasNumber = False

hasSpecial = False
